name: 'ovara'
version: '1.0.0'
config-version: 2

profile: 'ovara'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

flags:
  send_anonymous_usage_stats: false
  partial_parse: true

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ovara:
    stg:
      +schema: stg
      +materialized: incremental
      +incremental_strategy: 'append'
      +on_schema_change: append_new_columns
      +indexes:
        - columns: ['dw_metadata_dbt_copied_at']
        - columns: ['dw_metadata_stg_stored_at']
      +docs:
        node_color: "#2c7790"
      +pre-hook:
        - "{{ stg_start() }}"
      +tags: stg
    dw:
      +schema: dw
      # materialized=incremental set in dw macro
      +indexes:
        - columns: ['dw_metadata_dw_stored_at']
      +docs:
        node_color: "#2c7790"
      +post-hook:
        - "{{ dw_end() }}"
      +tags: dw

    int:
      +schema: int
      +materialized: table
      +docs:
        node_color: "#20586a"
    pub:
      +schema: pub
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
      +tags: pub
      koodisto:
        +tags: koodisto

