name: 'ovara'
version: '1.0.0'
config-version: 2

profile: 'ovara'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

flags:
  send_anonymous_usage_stats: false
  partial_parse: true

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ovara:
    stg:
      +schema: stg
      +materialized: incremental
      +incremental_strategy: 'append'
      +indexes:
        - columns: ['dw_metadata_dbt_copied_at']
        - columns: ['dw_metadata_stg_stored_at']
      +docs:
        node_color: "#00008b"

    dw:
      +schema: dw
      # materialized=incremental set in dw macro
      +indexes:
        - columns: ['dw_metadata_dw_copied_at']
      +docs:
        node_color: "#00008b"
    int:
      +schema: int
      +materialized: table
      +docs:
        node_color: "#ADD8E6"
    pub:
      +schema: pub
      +materialized: table
