ovara:
  target: test
  outputs:
    test:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST_TEST') }}"
      user: "{{ env_var('DBT_USERNAME_TEST') }}"
      password: "{{ env_var('DBT_PASSWORD_TEST') }}"
      port: "{{ env_var('DBT_PORT_TEST') | int }}"
      database: ovara
      schema: "{{ env_var('POSTGRES_SCHEMA_TEST') }}"
      threads: 8
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST_PROD') }}"
      user: "{{ env_var('DBT_USERNAME_PROD') }}"
      password: "{{ env_var('DBT_PASSWORD_PROD') }}"
      port: "{{ env_var('DBT_PORT_PROD') | int }}"
      database: ovara
      schema: pub
      threads: 8
